### ISSUE TITLE
 The path is empty

### ISSUE THREAD

**Issue by mosentest** [LukeFZ/Il2CppInspectorRedux#2]
Unhandled exception. System.ArgumentException: The path is empty. (Parameter 'path')
at System.IO.Path.GetFullPath(String path)
at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
at Il2CppInspector.CLI.App.Run(Options options) in D:\Downloads\Il2CppInspectorRedux\Il2CppInspector.CLI\Program.cs:line 179
at Il2CppInspector.CLI.App.<>c.

b__7_1(Options options) in D:\Downloads\Il2CppInspectorRedux\Il2CppInspector.CLI\Program.cs:line 154
at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult1 result, Action1 action)
at Il2CppInspector.CLI.App.Main(String[] args) in D:\Downloads\Il2CppInspectorRedux\Il2CppInspector.CLI\Program.cs:line 154
这个问题，要怎么解决呀，老哥

**Comment by mosentest** [comment]
D:\Downloads\Il2CppInspectorRedux\Il2CppInspector.CLI\bin\Release\net8.0\win-x64\publish>Il2CppInspector.exe  -i D:\qq\709847739\FileRecv\MobileFile\Super_Spider_Hero_3D_1.0.3_apks.apk -h D:\qq\709847739\FileRecv\MobileFile\Super_Spider_Hero_3D_1.0.3_apks\app\src\main\cpp\Il2cpp-Scaffolding -e none -c D:\qq\709847739\FileRecv\MobileFile\Super_Spider_Hero_3D_1.0.3_apks\app\src\main\cpp\ScaffoldingHelper\help.cs -p D:\qq\709847739\FileRecv\MobileFile\Super_Spider_Hero_3D_1.0.3_apks\app\src\main\cpp\ScaffoldingHelper\help.py -oD:\qq\709847739\FileRecv\MobileFile\Super_Spider_Hero_3D_1.0.3_apks\app\src\main\cpp\ScaffoldingHelper\help.json
Unhandled exception. System.ArgumentException: The path is empty. (Parameter 'path')
   at System.IO.Path.GetFullPath(String path)
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at Il2CppInspector.CLI.App.Run(Options options) in D:\Downloads\Il2CppInspectorRedux\Il2CppInspector.CLI\Program.cs:line 179
   at Il2CppInspector.CLI.App.<>c.<Main>b__7_1(Options options) in D:\Downloads\Il2CppInspectorRedux\Il2CppInspector.CLI\Program.cs:line 154
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Il2CppInspector.CLI.App.Main(String[] args) in D:\Downloads\Il2CppInspectorRedux\Il2CppInspector.CLI\Program.cs:line 154

D:\Downloads\Il2CppInspectorRedux\Il2CppInspector.CLI\bin\Release\net8.0\win-x64\publish>

**Comment by mosentest** [comment]
`D:\Downloads\Il2CppInspectorRedux\Il2CppInspector.CLI\bin\Release\net8.0\win-x64\publish>Il2CppInspector.exe  -i D:\qq\709847739\FileRecv\MobileFile\Super_Spider_Hero_3D_1.0.3_apks.apk -h D:\qq\709847739\FileRecv\MobileFile\Super_Spider_Hero_3D_1.0.3_apks\app\src\main\cpp\Il2cpp-Scaffolding -e none -c D:\qq\709847739\FileRecv\MobileFile\Super_Spider_Hero_3D_1.0.3_apks\app\src\main\cpp\ScaffoldingHelper\help.cs -p D:\qq\709847739\FileRecv\MobileFile\Super_Spider_Hero_3D_1.0.3_apks\app\src\main\cpp\ScaffoldingHelper\help.py -oD:\qq\709847739\FileRecv\MobileFile\Super_Spider_Hero_3D_1.0.3_apks\app\src\main\cpp\ScaffoldingHelper\help.json
Unhandled exception. System.ArgumentException: The path is empty. (Parameter 'path')
   at System.IO.Path.GetFullPath(String path)
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at Il2CppInspector.CLI.App.Run(Options options) in D:\Downloads\Il2CppInspectorRedux\Il2CppInspector.CLI\Program.cs:line 179
   at Il2CppInspector.CLI.App.<>c.<Main>b__7_1(Options options) in D:\Downloads\Il2CppInspectorRedux\Il2CppInspector.CLI\Program.cs:line 154
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Il2CppInspector.CLI.App.Main(String[] args) in D:\Downloads\Il2CppInspectorRedux\Il2CppInspector.CLI\Program.cs:line 154

D:\Downloads\Il2CppInspectorRedux\Il2CppInspector.CLI\bin\Release\net8.0\win-x64\publish>`

**Comment by LukeFZ** [comment]
Should be fixed as of 0426380
